---
kind: pipeline
type: docker
name: default

steps:
  - name: d9
    image: qwe1/dind-ansible-molecule:2.9-root
    environment:
      MOLECULE_DISTRO: "qwe1/docker-debian:9-nonfree-molecule"
    volumes:
      - name: dsock
        path: /var/run/docker.sock
    commands:
      - ls -lah
      - pwd
      - env
      - mkdir -p ~/.ansible/roles && cp -aR "$(pwd)" ~/.ansible/roles/richardskumat.ansible_role_chrome
      - molecule test

  - name: d10
    image: qwe1/dind-ansible-molecule:2.9-root
    environment:
      MOLECULE_DISTRO: "qwe1/docker-debian:10-nonfree-molecule"
    volumes:
      - name: dsock
        path: /var/run/docker.sock
    commands:
      - ls -lah
      - pwd
      - env
      - mkdir -p ~/.ansible/roles && cp -aR "$(pwd)" ~/.ansible/roles/richardskumat.ansible_role_chrome
      - molecule test

  - name: d11
    image: qwe1/dind-ansible-molecule:2.9-root
    environment:
      MOLECULE_DISTRO: "qwe1/docker-debian:11-nonfree-molecule"
    volumes:
      - name: dsock
        path: /var/run/docker.sock
    commands:
      - ls -lah
      - pwd
      - env
      - mkdir -p ~/.ansible/roles && cp -aR "$(pwd)" ~/.ansible/roles/richardskumat.ansible_role_chrome
      - molecule test

volumes:
  - name: dsock
    host:
      path: /var/run/docker.sock
