---
image: qwe1/dind-ansible-molecule:2.12.7

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  ROLE_NAME: ansible-role-chrome
  GALAXY_USERNAME: richardskumat
  GALAXY_ROLENAME: ansible_role_chrome

services:
  - docker:dind

stages:
  - test

before_script:
  - docker info
  - ansible --version
  - molecule --version
  - cd ..
  - cp -aR $ROLE_NAME $GALAXY_USERNAME.$GALAXY_ROLENAME
  - cd $GALAXY_USERNAME.$GALAXY_ROLENAME

test_d11:
  stage: test
  variables:
    MOLECULE_DISTRO: "qwe1/docker-debian:11-nonfree-molecule"
  script:
    - molecule test
